trigger: 
  tags:
    include:
    - "v*"
  paths:
    include:
    - docker/src/*
    - docker/Dockerfile

resources:
  repositories:
  - repository: "templates"
    type: git
    name: Kubernetes/kpe-base-pipelines

jobs:
- template: docker/standard-build-ap.yml@templates
  parameters:
    docker_image: 'kpe-seeker-injector'
    seeker_tech: 'golang'