parameters:
  - name: image
    displayName: Docker image name
    type: string
    default: 'dfi-seeker-injector'
  - name: trivy_version
    displayName: Version of tirivy to install
    type: string
    default: 0.19.2

variables:
  - name: seeker_server_url
    value: https://seeker.npd.telstrahealth.com:8096
  - name: seeker_project_key
    value: THUK-KPE-TEST

trigger: 
  tags:
    include:
    - "v*"
  paths:
    include:
    - docker/src/*
    - docker/Dockerfile

stages:
- stage: build_docker
  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-20.04'
  jobs:
  - job: build
    steps:
    - task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
      displayName: Setup GitVersion
      inputs:
        versionSpec: 5.x
    - task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
      displayName: Calculate version
      inputs:
        configFilePath: GitVersion.yml
    - bash: |
        curl -L https://github.com/aquasecurity/trivy/releases/download/v"$TRIVY_VER"/trivy_"$TRIVY_VER"_Linux-64bit.tar.gz -o trivy.tar.gz
        tar -zxf trivy.tar.gz
        #cp trivy /home/vsts/.local/bin/trivy
      displayName: Install Trivy
      env:
        TRIVY_VER: ${{ parameters.trivy_version }}
    - task: DockerInstaller@0
      displayName: 'Install Docker'
      inputs:
        dockerVersion: '19.03.2'
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure Backend Storage'
        KeyVaultName: 'kubernetes-secret-store'
        SecretsFilter: 'seeker-project-token'
        RunAsPreJob: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Azure Docker Registry'
        repository: ${{ parameters.image }}
        command: build
        arguments: --build-arg SEEKER_ACCESS_TOKEN=$(seeker-project-token) --build-arg SEEKER_SERVER_URL=${{ variables.seeker_server_url}} --build-arg SEEKER_PROJECT_KEY=${{ variables.seeker_project_key }} --build-arg SEEKER_AGENT_NAME=${{ parameters.image }}
        Dockerfile: ./docker/Dockerfile
        tags: |
          $(GitVersion.SemVer)
    - bash: |
        ./trivy drfostercontainerreg.azurecr.io/${{ parameters.image}}:$(GitVersion.SemVer)
      displayName: Run image secuirty scan
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Azure Docker Registry'
        repository: ${{ parameters.image }}
        command: push
        Dockerfile: ./docker/Dockerfile
        tags: |
          $(GitVersion.SemVer) 
        