trigger: 
  tags:
    include:
    - "v*"
  paths:
    include:
    - docker/src/*
    - docker/Dockerfile

resources:
  repositories:
  - repository: "templates"
    type: git
    name: Kubernetes/kpe-base-pipelines

extends:
  template: docker/standard-build-ap.yml@templates
  parameters:
    docker_image: 'kpe-seeker-injector'
    docker_file: 'docker/Dockerfile'
    seeker_enabled: "false"