trigger:
  tags:
    include:
    - "v*"
  paths:
    include:
    - charts/*

resources:
  repositories:
  - repository: templates
    type: git
    name: Kubernetes/kpe-base-pipelines

extends:
  template: helm/standard-build-ap.yml@templates
  parameters:
    helm_chart_name: "seeker-injector"
    on_prem_pool: 
      name: "on-prem"
    HELM_EXPERIMENTAL_OCI: "1"
