namespace: seeker

webhookName: thuk-seeker-injector
service: thuk-seeker-injector
webhook:
  timeoutSeconds: 5

rbac:
  enabled: true
  name: seeker-injector
  serviceAccount:
    create: true
    name: seeker-injector