namespace: seeker

service: 
  name: thuk-seeker-injector
  port: 443

webhook:
  name: thuk-seeker-injector
  timeoutSeconds: 5

rbac:
  enabled: true
  name: seeker-injector

serviceAccount:
  create: true
  name: seeker-injector

sidecar:
  repo: drfostercontainerreg.azurecr.io/kpe-seeker
  version: "0.2.2"

deployment:
  name: seeker-injector
  replicas: 1
  args: {}
  port: 8443

labels:
  owner: "KPE"

image:
  repo: drfostercontainerreg.azurecr.io/dfi-seeker-injector 
  tag: ""
  pullSecrets:
  - name: drfostercontainerreg