namespace: seeker
annotations: {}
labels: {}

service: 
  name: seeker-injector
  port: 443

webhook:
  name: seeker-injector
  timeoutSeconds: 5

rbac:
  enabled: true
  name: seeker-injector

serviceAccount:
  create: true
  name: seeker-injector

sidecar:
  registry: ""
  repo: ""
  version: ""
  imagePullSecrets: {}
  imagePullPolicy: IfNotPresent

deployment:
  name: seeker-injector
  replicas: 1
  args: {}
  port: 8443

image:
  registry: ""
  repo: "" 
  tag: ""
  imagePullSecrets: {}
  imagePullPolicy: IfNotPresent
