apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}
data:
  sidecarconfig.yaml: |
    containers:
      - name: seeker
        image: {{ include "sidecar.image" . }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: seeker-dir
          mountPath: /data/seeker
    volumes:
    - name: seeker-dir
      emptyDir: {}
    volumeMounts:
    - name: seeker-dir
      mountPath: /data/seeker
