apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}
data:
  sidecarconfig.yaml: |
    containers:
      - name: seeker
        image: {{ .Values.image.repo }}
        imagePullPolicy: IfNotPresent
