apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}
data:
  sidecarconfig.yaml: |
    containers:
      - name: seeker
        imagePullPolicy: IfNotPresent
        command: ["cp", "-r", "$SEEKER_LOCATION", "/run/seeker"]
        volumeMounts:
        - name: seeker-dir
          mountPath: /run/seeker
    volumes:
    - name: seeker-dir
      emptyDir: {}
    volumeMounts:
    - name: seeker-dir
      mountPath: /run/seeker
    initImage:
      repo: {{ .Values.sidecar.repo }}
      version: {{ .Values.sidecar.version }}
