apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{ include "common.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "common.labels" . | nindent 8 }}
    spec:
      {{ if .Values.image.pullSecrets -}}
      imagePullSecrets:
      {{ toYaml .Values.image.pullSecrets | nindent 6}}
      {{- end }}
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ include "deployment.image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - -v=4
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.deployment.name }}
        - name: webhook-config
          configMap:
            name: {{ .Values.deployment.name }}
