{{- $host := printf "%s.%s.svc" .Values.service.name .Values.namespace }}
{{- $ca := genSelfSignedCert $host (list) (list $host) 365 }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc (trim $ca.Cert) }}
  tls.key: {{ b64enc (trim $ca.Key) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
webhooks:
- name: {{ .Values.webhook.name }}
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ b64enc (trim $ca.Cert) }}
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Values.namespace }}
      path: /mutate
      port: {{ .Values.service.port }}
  failurePolicy: Ignore
  matchPolicy: Equivalent
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: "*"
  sideEffects: None
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  namespaceSelector:
    matchLabels:
      seeker.injector/enabled: true