apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.port }}
  selector:
    {{ include "common.labels" . | nindent 4 }}
